### ISSUE TITLE
Check against known badge URLs

### ISSUE THREAD

**Issue by maxdeviant** [defunctzombie/badginator#7]
Should badginator check against known URLs for serving badges to prevent false positives (e.g., a non-badge PNG that links somewhere)?

**Comment by defunctzombie** [comment]
@maxdeviant that is one approach tho I was hesitant to do that cause I would need to start maintaining a master list of badge URL (which may not be that terrible but seems like it could discourage use).

I've actually been working on a solution which uses image analysis to determine if the actual image served by the URL is a badge. Maybe a combination of a URL master list and this technique can be used.

Hoping to get improved recognition out this week so the readme regex hack can be removed since it is unreliable.

**Comment by maxdeviant** [comment]
Maintaining a master list doesn't sound like fun, but it's probably the simplest way.

Image analysis would be a much cooler solution though :smile:

**Comment by defunctzombie** [comment]
Commented in #1 with progress.
